add preferred client mode
privacyidea/csharp-client pull request #4
Opened 2022-11-22 09:16 UTC by lukasmatusiewicz

- make use of `preferred_client_mode`
- update tests
- fix dependencies
- update naming as provided by the convention
- handle lost `multi_challenge` data
- convert `ServiceAccountAvailable` method to the inline code (only one usage)
- boundle GetAuthToken's content into an if-else statement

Closing #3

2022-11-22 09:17 UTC, lukasmatusiewicz commented
@nilsbehlen , should this commented code be removed, or fixed, or should stay as it is?
https://github.com/privacyidea/csharp-client/blob/main/PrivacyIDEA_Client/PrivacyIDEA.cs#L327

2022-11-22 15:18 UTC, nilsbehlen requested changes
remove the Microsoft.IdentityServer.Web.dll please

2022-11-22 15:18 UTC, nilsbehlen commented on PrivacyIDEA_Client/PIResponse.cs
> +                                if (privacyIDEA != null)
use pattern matching here too, should be consistent everywhere.

2022-11-22 15:18 UTC, nilsbehlen commented on PrivacyIDEA_Client/PIResponse.cs
> +                                        if (signRequest != null)
use pattern matching

2022-11-22 15:18 UTC, nilsbehlen commented on PrivacyIDEA_Client/PIResponse.cs
> +                    if (detail["preferred_client_mode"] is not null)
if (detail["preferred_client_mode"] is string pref_client_mode)

2022-11-22 15:18 UTC, nilsbehlen commented on PrivacyIDEA_Client/PIResponse.cs
> +                    if (detail["transaction_id"] is not null)
same as above

2022-11-22 15:18 UTC, nilsbehlen commented on PrivacyIDEA_Client/PrivacyIDEA.cs
> +                        if (tkn["token"] is not null)
pattern matching

2022-11-22 15:18 UTC, nilsbehlen commented on PrivacyIDEA_Client/PrivacyIDEA.cs
> +                // todo rm?
you can remove the old code

2022-11-22 15:18 UTC, nilsbehlen commented on Tests/Tests.csproj
> +	<ItemGroup>
i don't think this file is needed - if it is, there is a problem somehwere

2022-12-06 11:05 UTC, nilsbehlen approved these changes

2022-12-06 11:05 UTC, merged